version: "3.7"

services:

  api-gateway:
    image: api-gateway
    container_name: gateway-service
    networks:
      - cab_aggregator
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - eureka-service
    ports:
      - '8070:8070'

  rating_service:
    image: rating-service
    container_name: rating-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/rating
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs

    ports:
      - '8083:8083'
    networks:
      - cab_aggregator
    depends_on:
      - eureka-service
      - mysql_db
      - logstash

  payment-service:
    image: payment-service
    container_name: payment-service
    environment:
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/payment
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs

    ports:
      - '8085:8085'
    networks:
      - cab_aggregator
    depends_on:
      - eureka-service
      - mysql_db
      - logstash


  ride_service:
    image: ride-service
    container_name: ride-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/rides
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs

    ports:
      - '8082:8082'
    networks:
      - cab_aggregator
    depends_on:
      - eureka-service
      - mysql_db
      - kafka
      - logstash


  driver_service:
    image: driver-service
    container_name: driver-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/drivers
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs

    ports:
      - '8084:8084'
    networks:
      - cab_aggregator
    depends_on:
      - eureka-service
      - mysql_db
      - kafka
      - logstash


  mysql_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - cab_aggregator
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./db:/docker-entrypoint-initdb.d

  passenger_service:
    image: passenger-service
    container_name: passenger-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/passengers
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs

    ports:
      - '8081:8081'
    networks:
      - cab_aggregator
    depends_on:
      - eureka-service
      - mysql_db
      - logstash


  eureka-service:
    image: eureka-server
    container_name: eureka-server
    networks:
      - cab_aggregator
    ports:
      - '8090:8090'


  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
      - cab_aggregator
    ports:
      - "2181:2181"

  kafka:
      image: obsidiandynamics/kafka
      container_name: kafka
      restart: "no"
      networks:
        - cab_aggregator
      ports:
        - "9092:9092"
      environment:
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
        KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      depends_on:
        - zookeeper


  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    networks:
      - cab_aggregator
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    networks:
      - cab_aggregator
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasource
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

  promo_code_service:
    image: promo-code-service
    container_name: promo-code-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/promocode
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8090/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs


    ports:
      - '8086:8086'
    networks:
      - cab_aggregator
    depends_on:
      - eureka-service
      - mysql_db
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - cab_aggregator


  kibana:
    image: kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - cab_aggregator


  logstash:
    image: logstash:8.12.0
    container_name: logstash
    volumes:
      - ./monitoring/logstash/config:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - cab_aggregator

  zipkin:
    image: openzipkin/zipkin:2.27
    container_name: zipkin
    networks:
      - cab_aggregator
    ports:
      - '9411:9411'

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - '8080:8080'
    networks:
      - cab_aggregator
    command:
      - start-dev
  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  cab_aggregator:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local