feign:
  okhttp:
    enabled=true:
  client:
    driver:
      name: driver
      url: http://localhost:8084
      path: /api/v1/drivers
    ride:
      name: ride
      url: http://localhost:8080
      path: /api/v1/rides



