spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drivers
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cab-aggregator-realm
          jwk-set-uri: http://localhost:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:9092
      group-id: ride-creation-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
topic:
    name:
      ride: ride
      driver: driver
      available: available
kafka:
  partitions:
    count: 1
  replicas:
    count: 1
service:
    rating:
      name: rating
      path: /api/v1/rating
    park:
      name: park
      path: /api/v1/car-park
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka


management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
jwt:
  auth:
    converter:
      resource-id: cab-aggregator-client
      principal-attribute: sub