scrape_configs:
  - job_name: 'cab-aggregator-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:8081',
                  'host.docker.internal:8082',
                  'host.docker.internal:8083',
                  'host.docker.internal:8084',
                  'host.docker.internal:8085',
                  'host.docker.internal:8086',
                  'host.docker.internal:8087']
        labels:
          application: 'cab-aggregator-app'