spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passengers
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: passenger
service:
    rating:
      name: rating
      path: /api/v1/rating
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka


management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true