spring:
  datasource:
    url: jdbc:mysql://localhost/passengers
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
feign:
  client:
    rating:
      name: rating
      url: http://localhost:8083
      path: /api/v1/rating
server:
  port: 8081

