spring:
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://driver
          predicates:
            - Path=/api/v1/drivers/**
          filters:
            - name: CircuitBreaker
              args:
                name: driver-service-fallback
                fallbackUri: forward:/fallback/drivers-service


        - id: passenger-service
          uri: lb://passenger
          predicates:
            - Path=/api/v1/passengers/**
          filters:
            - name: CircuitBreaker
              args:
                name: passengers-service-circuit
                fallbackUri: forward:/fallback/passengers-service


        - id: ride-service
          uri: lb://ride
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - name: CircuitBreaker
              args:
                name: ride-service-circuit
                fallbackUri: forward:/fallback/rides-service


        - id: payment-service
          uri: lb://payment
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit
                fallbackUri: forward:/fallback/payment-service


        - id: rating-service
          uri: lb://rating
          predicates:
            - Path=/api/v1/rating/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit
                fallbackUri: forward:/fallback/rating-service


        - id: promo-code-service
          uri: lb://promo-code
          predicates:
            - Path=/api/v1/promo-code/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit
                fallbackUri: forward:/fallback/promo-code-service


